name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-and-evaluate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade scikit-learn
          pip install -r requirements.txt

      - name: Lint code
        run: flake8 .

      - name: Train model
        working-directory: .
        run: |
          mkdir -p app
          python train.py

      - name: Run unit tests
        run: pytest

      - name: Evaluate trained model
        working-directory: .
        run: |
          python app/evaluate.py

      - name: Upload model artifact
        uses: actions/upload-artifact@v4
        with:
          name: model-artifact
          path: app/model.joblib
